# This file was generated by GoReleaser. DO NOT EDIT.
cask "ferry" do
  postflight_steps do
    run "/usr/bin/xattr",
        args:         ["-dr", "com.apple.quarantine", "{{staged_path}}/ferry"],
        must_succeed: false
  end

  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "d00f6b3cb99eb7f7a1a31ae120eda1d69cb0b9f7c84bcc829e3075d3128fab99"
      url "https://github.com/LucasStbnr/ferry/releases/download/v#{version}/ferry_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "77a780a7e571f61c8e430d18553bce6edf12319e2b76ba20894b0048ddedd42f"
      url "https://github.com/LucasStbnr/ferry/releases/download/v#{version}/ferry_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "064de0c0e5d43150f52d165a2bc480ffa1fd63a86fbd8dc03c462f496683d195"
      url "https://github.com/LucasStbnr/ferry/releases/download/v#{version}/ferry_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "34916f69a6d316e1847cf2232b81c33388ad3ce66a288cae10a007aa130f91b2"
      url "https://github.com/LucasStbnr/ferry/releases/download/v#{version}/ferry_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ferry"
  desc "IMAP and SMTP bridge that puts a Resend account into any mail client"
  homepage "https://github.com/LucasStbnr/ferry"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ferry"

  uninstall launchctl: [
      "io.github.lucasstbnr.ferry",
    ]

  zap trash: [
      "~/Library/Application Support/ferry",
      "~/Library/LaunchAgents/io.github.lucasstbnr.ferry.plist",
    ]

  caveats <<~EOS
    Ferry serves IMAP and SMTP over TLS on loopback, for any mail client.

    Getting started:

      ferry account add mysite      add a Resend account; the app password
                                    is printed once
      ferry trust                   trust Ferry's local certificate so mail
                                    clients connect without a warning
      ferry service install         run it in the background from now on

    On macOS, `ferry mail-profile --open` configures Apple Mail in one
    double-click. Any other client is set up by hand against localhost;
    `ferry account add` prints the ports and credentials.

    Mail is stored under
      ~/Library/Application Support/ferry

    That directory is the only copy of your read state, folders and drafts:
    Resend does not store them. Back it up, and keep FileVault on.
  EOS
end
