# This file was generated by GoReleaser. DO NOT EDIT.
cask "ferry" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "bf19744c8e7fa6e603683e5502eb62cb208f478b031d164df98df69dac650792"
      url "https://github.com/LucasStbnr/ferry/releases/download/v#{version}/ferry_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "986b40afaad1ca3f7a77e5c856c51abec40aa315df1746410fb17cfd8d8fd5cf"
      url "https://github.com/LucasStbnr/ferry/releases/download/v#{version}/ferry_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "32c1afef6cfd6603da91c89832f10066794810adc20d6896a948c2f7caa8298b"
      url "https://github.com/LucasStbnr/ferry/releases/download/v#{version}/ferry_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "bb426f87cb0c1c8be46d833441e84120ee26b66ac111f42c78eaefeb38630159"
      url "https://github.com/LucasStbnr/ferry/releases/download/v#{version}/ferry_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ferry"
  desc "IMAP and SMTP bridge that puts a Resend account into any mail client"
  homepage "https://github.com/LucasStbnr/ferry"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ferry"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"], print_stderr: false).exit_status.zero?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ferry"]
    end
  end

  uninstall launchctl: [
      "io.github.lucasstbnr.ferry",
    ]

  zap trash: [
      "~/Library/Application Support/ferry",
      "~/Library/LaunchAgents/io.github.lucasstbnr.ferry.plist",
    ]

  caveats <<~EOS
    Ferry serves IMAP and SMTP over TLS on loopback, for any mail client.

    Getting started:

      ferry account add mysite      add a Resend account; the app password
                                    is printed once
      ferry trust                   trust Ferry's local certificate so mail
                                    clients connect without a warning
      ferry service install         run it in the background from now on

    On macOS, `ferry mail-profile --open` configures Apple Mail in one
    double-click. Any other client is set up by hand against localhost;
    `ferry account add` prints the ports and credentials.

    Mail is stored under
      ~/Library/Application Support/ferry

    That directory is the only copy of your read state, folders and drafts:
    Resend does not store them. Back it up, and keep FileVault on.
  EOS
end
